### ISSUE TITLE
Returns failure when system is connected to LAN but Internet is still connected through Wi-Fi

### ISSUE THREAD

**Issue by keepitopen** [aankur/check-internet-connected#11]
I have a system which is connected through to other systems as well and Internet is connected through Wi-Fi. checkInternetConnected() returns a failure in such a case. Any idea how to solve that?

**Comment by aankur** [comment]
Does ping or nslookup work for you

**Comment by keepitopen** [comment]
@aankur you were right. The issue wasn't lan but the user environment variables were gobbled up. Sorry for opening an issue. Closing with this comment.
