### ISSUE TITLE
Timeout value does not seem to be read

### ISSUE THREAD

**Issue by icarus31** [aankur/check-internet-connected#3]
Hi,

I tried your module and whatever timeout I put, I get the catch right away. I thought it will wait to the value put in the timeout, no? Though, I think the retry works.

Maybe I did not understand properly what the field timeout is used. Would you mind to explain me?

**Comment by icarus31** [comment]
I answered myself!

**Comment by aankur** [comment]
timeout is the maximum time you will have to wait for the request to timeout.
